//init store
export const state = () => ({
  imagePlaceholder: "data:image/jpeg;base64,/9j/2wCEAAIBAQEBAQIBAQIDAgECAwMCAgICAwMDAwMDAwMFAwQEBAQDBQUFBgYGBQUHBwgIBwcKCgoKCgwMDAwMDAwMDAwBAgICBAMEBwUFBwoIBwgKDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDP/dAAQAFP/uAA5BZG9iZQBkwAAAAAH/wAARCABaAKADABEAAREBAhEB/8QATQABAQAAAAAAAAAAAAAAAAAAAAgBAQEBAAAAAAAAAAAAAAAAAAAEBRABAAAAAAAAAAAAAAAAAAAAABEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAAABEQIRAD8AkdW0QAAAAAAAAAAAAAAAAAAH/9CR1bRAAAAAAAAAAAAAAAAAAAf/0ZHVtEAAAAAAAAAAAAAAAAAAB//SkdW0QAAAAAAAAAAAAAAAAAAH/9OR1bRAAAAAAAAAAAAAAAAAAAf/1JHVtEAAAAAAAAAAAAAAAAAAB//VkdW0QAAAAAAAAAAAAAAAAAAH/9aR1bRAAAAAAAAAAAAAAAAAAAf/15HVtEAAAAAAAAAAAAAAAAAAB//QkdW0QAAAAAAAAAAAAAAAAAAH/9GR1bRAAAAAAAAAAAAAAAAAAAf/0pHVtEAAAAAAAAAAAAAAAAAAB//Z",
})

export const getters = {
  getImagePlaceholder(state) {
    return state.imagePlaceholder;
  },
}

export const mutations = {
}
